backend:
  name: git-gateway

media_folder: static/images
public_folder: images

media_library:
  name: cloudinary
  config:
    cloud_name: creativecodebudapest
    api_key: 875789426415856
    default_transformations: 
      - breakthumbnails

collections:
  - name: event
    label: Event
    folder: static/events
    create: true
    fields:
      - name: title 
        label: Title
      - name: date
        label: Date
        widget: datetime
        required: false
      - name: location
        label: Location
        required: false
      - name: googleMapsLink
        label: Google Maps Link
        required: false
      - name: meetupEventLink
        label: Meetup Event Link
        required: false
      - name: facebookEventLink
        label: Facebook Event Link
        required: false
      - name: poster
        label: Poster
        widget: image
        required: false
      - name: posterGravity
        label: Poster Crop Gravity
        hint: 'Specifies where to crop the poster. Valid values: north_east, north, north_west, west, south_west, south, south_east, east, or center.'
        required: false
      - name: body
        label: Description
        widget: markdown
        required: false
      - name: speakers
        label: Speakers
        widget: list
        required: false
        fields:
          - label: Name
            name: name
            required: false
          - label: Image
            name: image
            widget: image
            required: false
          - label: Bio
            name: bio
            widget: markdown
            required: false
      - name: photos
        label: Photos
        widget: image
        required: false
        allow_multiple: true
        media_library:
          config:
            multiple: true
            max_files: 500
      - name: widePhotos
        label: Wide photos
        hint: Indexes of photos to enlarge. Comma separeted list. (eg. 1,13,25)
        widget: list
        required: false
      - name: fullWidthPhotos
        label: Full width photos
        hint: Indexes of photos to enlarge to full width. Comma separeted list. (eg. 1,13,25)
        widget: list
        required: false
